### PR TITLE
forward more methods to the collection in the emulation layer

### PR DESCRIPTION
**Pull request by codekitchen**
We already forward `each` to the collection, so including `Enumerable`
allows more code written against the original ActiveModel
ErrorCollection class to continue working without modification.

### CODE REVIEW

**Comment by aq1018** [comment]
I don't think the original `ActiveModel::Errors` API includes `Enumerable` module. This gem aims to mirror the original API, and I'm reluctant to do add extra APIs.

However, that doesn't stop you from adding it in yourself by running during your app initialization or in a rails initializer:

``` ruby
ActiveModel::BetterErrors::Errors.send(:include, Enumerable)
```

**Comment by aq1018** [comment]
Taking my words back. Just checked the latest `ActiveModel::Errors` [code](https://github.com/rails/rails/blob/8c9498140e3ddecd9afef2df99ecf6ab25437f63/activemodel/lib/active_model/errors.rb#L58) and it does include `Enumerable`. Will merge it in now.

**Comment by aq1018** [comment]
v1.6.7 released.

**Comment by codekitchen** [comment]
Cool thank you. Yeah this comes directly from a failing test in our rails app after adding better_errors, the code used `model.errors.map { ... }`

**Comment by aq1018** [comment]
What?! U haz tests?!  And workz?!

Jokes aside, glad that your tests worked! :D

**Pull request merged**
